#!/bin/bash
# FBT Code Assistant - Like Copilot/Claude for Flipper Zero Development
# Helps build Flipper Zero apps with FBT

set -e

FBT_DIR="/opt/fbt"
FLIPPER_APPS_DIR="/opt/flipper-zero/apps"
ASSISTANT_LOG="/var/log/fbt-assistant.log"

log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1" | tee -a "$ASSISTANT_LOG"
}

show_header() {
    clear
    echo "=========================================="
    echo "  FBT Code Assistant for Flipper Zero"
    echo "  Like Copilot/Claude for Flipper Dev"
    echo "=========================================="
    echo ""
}

install_fbt() {
    log "Installing FBT (Flipper Build Tool)..."
    
    # Install dependencies
    apt-get update -qq
    apt-get install -y \
        python3 python3-pip \
        git \
        build-essential \
        libusb-1.0-0-dev \
        >/dev/null 2>&1
    
    # Clone FBT
    if [ ! -d "$FBT_DIR" ]; then
        git clone https://github.com/flipperdevices/flipperzero-firmware.git "$FBT_DIR"
    fi
    
    cd "$FBT_DIR"
    
    # Install FBT
    ./fbt --help >/dev/null 2>&1 || {
        pip3 install -r scripts/requirements.txt
    }
    
    log "✓ FBT installed"
}

create_app_template() {
    show_header
    echo "Create New Flipper Zero App"
    echo "==========================="
    echo ""
    read -p "App name: " app_name
    read -p "App description: " app_desc
    read -p "App category (system/games/tools): " app_category
    
    app_category=${app_category:-tools}
    app_dir="$FLIPPER_APPS_DIR/$app_category/$app_name"
    
    mkdir -p "$app_dir"
    
    # Create app.c
    cat > "$app_dir/$app_name.c" <<EOF
#include <furi.h>
#include <gui/gui.h>
#include <input/input.h>

typedef struct {
    FuriMessageQueue* input_queue;
    ViewPort* view_port;
    Gui* gui;
} ${app_name}_App;

static void draw_callback(Canvas* canvas, void* ctx) {
    UNUSED(ctx);
    canvas_clear(canvas);
    canvas_set_font(canvas, FontPrimary);
    canvas_draw_str(canvas, 10, 20, "$app_name");
    canvas_draw_str(canvas, 10, 35, "$app_desc");
}

static void input_callback(InputEvent* input_event, void* ctx) {
    FuriMessageQueue* queue = ctx;
    furi_message_queue_put(queue, input_event, FuriWaitForever);
}

int32_t ${app_name}_app(void* p) {
    UNUSED(p);
    
    ${app_name}_App* app = malloc(sizeof(${app_name}_App));
    
    app->input_queue = furi_message_queue_alloc(8, sizeof(InputEvent));
    app->view_port = view_port_alloc();
    app->gui = furi_record_open(RECORD_GUI);
    
    view_port_draw_callback_set(app->view_port, draw_callback, app);
    view_port_input_callback_set(app->view_port, input_callback, app->input_queue);
    
    gui_add_view_port(app->gui, app->view_port, GuiLayerFullscreen);
    
    InputEvent event;
    bool running = true;
    
    while(running) {
        if(furi_message_queue_get(app->input_queue, &event, FuriWaitForever) == FuriStatusOk) {
            if(event.type == InputTypePress && event.key == InputKeyBack) {
                running = false;
            }
        }
        view_port_update(app->view_port);
    }
    
    gui_remove_view_port(app->gui, app->view_port);
    view_port_free(app->view_port);
    furi_record_close(RECORD_GUI);
    furi_message_queue_free(app->input_queue);
    free(app);
    
    return 0;
}
EOF

    # Create application.fam
    cat > "$app_dir/application.fam" <<EOF
AppId("$app_name")
AppVersion("1.0")
AppDescription("$app_desc")
AppAuthor("GhostPi")
AppCategory($app_category)
EOF

    # Create Makefile
    cat > "$app_dir/Makefile" <<EOF
APP_ENTRY = ${app_name}_app
APP_SOURCES = ${app_name}.c
include \$(FBT_APPSDIR)/rules.mk
EOF

    echo ""
    echo "✓ App template created: $app_dir"
    echo ""
    echo "Build with:"
    echo "  cd $FBT_DIR"
    echo "  ./fbt app_${app_name}"
}

code_assistant() {
    show_header
    echo "FBT Code Assistant"
    echo "=================="
    echo ""
    echo "I can help you:"
    echo "  1) Generate Flipper Zero app code"
    echo "  2) Fix compilation errors"
    echo "  3) Add features to existing app"
    echo "  4) Optimize code"
    echo "  5) Create custom protocol"
    echo ""
    read -p "What do you need help with? " help_type
    
    case $help_type in
        1)
            echo ""
            read -p "What should the app do? " app_purpose
            echo ""
            echo "Generating code based on: $app_purpose"
            # Generate code suggestions
            echo "Here's a template for your app:"
            echo ""
            echo "// App purpose: $app_purpose"
            echo "// Generated by FBT Assistant"
            echo ""
            echo "// Add your implementation here"
            ;;
        2)
            read -p "Enter error message: " error_msg
            echo ""
            echo "Common fixes:"
            echo "  - Check includes: #include <furi.h>"
            echo "  - Check function signatures"
            echo "  - Verify FBT version compatibility"
            ;;
        *)
            echo "Feature coming soon"
            ;;
    esac
}

build_app() {
    show_header
    echo "Build Flipper Zero App"
    echo "======================"
    echo ""
    
    if [ ! -d "$FBT_DIR" ]; then
        echo "FBT not installed. Installing..."
        install_fbt
    fi
    
    echo "Available apps:"
    find "$FLIPPER_APPS_DIR" -name "*.c" -type f | head -10
    echo ""
    read -p "Enter app name to build: " app_name
    
    cd "$FBT_DIR"
    ./fbt "app_$app_name" 2>&1 | tee /tmp/fbt_build.log
    
    if [ ${PIPESTATUS[0]} -eq 0 ]; then
        echo ""
        echo "✓ Build successful!"
        echo "Firmware: $FBT_DIR/dist/f7/firmware/"
        
        # Copy to Flipper if mounted
        if [ -d "/mnt/flipper-zero" ] && mountpoint -q "/mnt/flipper-zero"; then
            cp "$FBT_DIR/dist/f7/firmware/"* "/mnt/flipper-zero/" 2>/dev/null && {
                echo "✓ Copied to Flipper Zero"
            }
        fi
    else
        echo ""
        echo "✗ Build failed. Check /tmp/fbt_build.log"
    fi
}

sync_to_flipper() {
    if [ -d "/mnt/flipper-zero" ] && mountpoint -q "/mnt/flipper-zero"; then
        echo "Syncing apps to Flipper Zero..."
        rsync -av "$FLIPPER_APPS_DIR/" "/mnt/flipper-zero/apps/" 2>/dev/null && {
            echo "✓ Synced to Flipper Zero"
        }
    else
        echo "Flipper Zero not mounted"
    fi
}

main_menu() {
    while true; do
        show_header
        echo "Main Menu:"
        echo "  1) Install/Update FBT"
        echo "  2) Create New App Template"
        echo "  3) Code Assistant (AI-like help)"
        echo "  4) Build App"
        echo "  5) Sync to Flipper Zero"
        echo "  6) View App Examples"
        echo "  0) Exit"
        echo ""
        read -p "Select option: " choice
        
        case $choice in
            1) install_fbt ;;
            2) create_app_template ;;
            3) code_assistant ;;
            4) build_app ;;
            5) sync_to_flipper ;;
            6) 
                echo "App examples in: $FLIPPER_APPS_DIR"
                find "$FLIPPER_APPS_DIR" -name "*.c" -type f | head -20
                ;;
            0) exit 0 ;;
            *) echo "Invalid option" ; sleep 1 ;;
        esac
        
        echo ""
        read -p "Press Enter to continue..."
    done
}

main_menu

