#!/bin/bash
# FBT (Flipper Build Tool) Helper
# Builds Flipper Zero apps with AI coding assistant support

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
FBT_DIR="${FBT_DIR:-/opt/flipper-build-tool}"
APP_DIR="${1:-$SCRIPT_DIR/../apps}"

log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] [FBT] $1"
}

install_fbt() {
    log "Installing Flipper Build Tool (FBT)..."
    
    # Install dependencies
    apt-get update -qq
    apt-get install -y \
        python3 python3-pip \
        git \
        build-essential \
        >/dev/null 2>&1
    
    # Clone FBT
    if [ ! -d "$FBT_DIR" ]; then
        log "Cloning FBT..."
        git clone https://github.com/flipperdevices/flipperzero-firmware.git "$FBT_DIR" 2>/dev/null || true
    fi
    
    cd "$FBT_DIR"
    
    # Install FBT
    ./fbt --help > /dev/null 2>&1 || {
        # Install Python dependencies
        pip3 install -r requirements.txt 2>/dev/null || true
    }
    
    log "✓ FBT installed"
}

build_app() {
    local app_name="$1"
    local app_path="$APP_DIR/$app_name"
    
    if [ ! -d "$app_path" ]; then
        log "Error: App not found: $app_path"
        return 1
    fi
    
    log "Building app: $app_name"
    
    cd "$FBT_DIR"
    
    # Build app
    ./fbt fap_$(echo $app_name | tr '[:upper:]' '[:lower:]') 2>&1 | tee /tmp/fbt-build.log || {
        log "Build failed. Check /tmp/fbt-build.log"
        return 1
    }
    
    log "✓ App built successfully"
    
    # Find built .fap file
    local fap_file=$(find "$FBT_DIR" -name "*.fap" -newer "$app_path" | head -1)
    
    if [ -n "$fap_file" ]; then
        log "Built file: $fap_file"
        echo "$fap_file"
    fi
}

ai_code_helper() {
    local task="$1"
    local language="${2:-c}"
    
    log "AI Coding Helper - Generating code..."
    log "Task: $task"
    
    # This would integrate with AI API (Claude, Copilot, etc.)
    # For now, generate template code
    
    local code_file="/tmp/ai-generated-$(date +%s).$language"
    
    case "$language" in
        c)
            cat > "$code_file" <<EOF
// AI Generated Code for: $task
// Generated by GhostPi AI Helper

#include <furi.h>
#include <gui/gui.h>

// TODO: Implement $task
// Use AI assistant to complete this code

int main() {
    // Your code here
    return 0;
}
EOF
            ;;
        python)
            cat > "$code_file" <<EOF
# AI Generated Code for: $task
# Generated by GhostPi AI Helper

# TODO: Implement $task
# Use AI assistant to complete this code

def main():
    pass

if __name__ == "__main__":
    main()
EOF
            ;;
    esac
    
    echo "$code_file"
    log "✓ Code template generated: $code_file"
    log "Edit this file and use AI assistant to complete it"
}

create_app_template() {
    local app_name="$1"
    local app_type="${2:-basic}"
    
    log "Creating Flipper Zero app template: $app_name"
    
    local app_dir="$APP_DIR/$app_name"
    mkdir -p "$app_dir"
    
    # Create app structure
    cat > "$app_dir/application.fam" <<EOF
App(
    appid="apps.$app_name",
    name="$app_name",
    apptype=FlipperAppType.EXTERNAL,
    entry_point="$(echo $app_name | tr '[:upper:]' '[:lower:]')_main",
    fap_category="Tools",
    fap_icon="icon.png",
    fap_icon_assets="assets",
)
EOF
    
    mkdir -p "$app_dir/src"
    cat > "$app_dir/src/$(echo $app_name | tr '[:upper:]' '[:lower:]').c" <<EOF
#include <furi.h>
#include <gui/gui.h>
#include <input/input.h>

// $app_name - Flipper Zero App
// Generated by GhostPi FBT Helper

int32_t $(echo $app_name | tr '[:upper:]' '[:lower:]')_main(void* p) {
    UNUSED(p);
    
    // Your app code here
    // Use AI helper to complete implementation
    
    return 0;
}
EOF
    
    log "✓ App template created: $app_dir"
    echo "$app_dir"
}

list_apps() {
    log "Available Flipper Zero apps:"
    echo ""
    
    if [ -d "$APP_DIR" ]; then
        find "$APP_DIR" -name "application.fam" -exec dirname {} \; | while read app_dir; do
            echo "  - $(basename $app_dir)"
        done
    else
        echo "  No apps found"
    fi
}

case "${1:-help}" in
    install)
        install_fbt
        ;;
    build)
        build_app "${2:-}"
        ;;
    create)
        create_app_template "${2:-}" "${3:-basic}"
        ;;
    list)
        list_apps
        ;;
    ai)
        ai_code_helper "${2:-}" "${3:-c}"
        ;;
    *)
        echo "FBT Helper - Flipper Zero Build Tool"
        echo ""
        echo "Usage: $0 {install|build|create|list|ai}"
        echo ""
        echo "Commands:"
        echo "  install              - Install FBT"
        echo "  build <app_name>    - Build an app"
        echo "  create <name> [type]- Create app template"
        echo "  list                - List available apps"
        echo "  ai <task> [lang]    - Generate code with AI helper"
        echo ""
        exit 1
        ;;
esac

